version: "3.8"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_OHgo9WsDN7Kz
      POSTGRES_DB: authen_service_db
    volumes:
      - db:/var/lib/postgresql/data

  authen-service:
    build: ./authen-service
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_OHgo9WsDN7Kz@ep-damp-water-abef069o-pooler.eu-west-2.aws.neon.tech/authen_service_db?sslmode=require
      JWT_SECRET: Hy7Xp9Qm2Lk4Zs6Nf8Vb
    depends_on:
      - db

  web:
    build: ./authen-web
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/trpc
    depends_on:
      - authen-service

volumes:
  db:
